### PR TITLE
Output is now printed by the framework

### PR DESCRIPTION
**Pull request by gbouv**

### CODE REVIEW

**Review by h4ck3rk3y — APPROVED** [review]

**Comment by h4ck3rk3y** [comment]
@gbouv are we printing input automatically? Or do we plan to?

**Comment by gbouv** [comment]
No we're not. And I think it's pretty useless to print the input given that it was sent by the user. An interesting thing would be to print the "input_with_defaults" but the "default injection"  is done by the user inside the script so we can't easily print it for them

**Comment by h4ck3rk3y** [comment]
In the original eth2-module we'd pretty print the JSON/YAML that was sent and that was useful as we'd use the --args $(cat test.yml)

Seeing it on the screen helped make sure that the input was the same and would catch empty inputs.

**Comment by gbouv** [comment]
Yeah then users can print it in there script if they want to? I mean, I am not opposed to it and it's also quite simple to do, but might be worth a discussion as it would significantly clutter the execution output for long config like for the eth2-module.

**Pull request merged**
